#!/bin/bash

BASEDIR="/home/rlp10/media"	# base directory of your media
DMENU_OPTIONS="-i"		# case insensitive
MEDIA_PLAYER="mplayer"		# media player
MEDIA_PLAYER_OPTIONS="-fs"	# full screen mode

TARGET="$BASEDIR"
while [[ -d "$TARGET" ]];do
	RESPONSE=$(echo -e ".\n..\n$(ls "$TARGET")\nquit" | dmenu $DMENU_OPTIONS)
	if [[ "$RESPONSE" == "quit" ]];then
		exit 1
	fi
	if [[ "$RESPONSE" == "." ]];then
		$MEDIA_PLAYER "$MEDIA_PLAYER_OPTIONS" "$TARGET/"*
		exit 0
	fi
	TARGET="$TARGET/$RESPONSE"
done
$MEDIA_PLAYER "$MEDIA_PLAYER_OPTIONS" "$TARGET"